version: 0.0
os: linux

files:
  - source: ./springbootCode/target/awesomeday4part1-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/springbootCode

hooks:
  BeforeInstall:
  - location: ./codedeploy/beforeInstall.sh
    timeout: 180
    runas: ubuntu
  AfterInstall:
  - location: ./codedeploy/afterInstall.sh
    timeout: 180
    runas: ubuntu
  ApplicationStart:
  - location: ./codedeploy/applicationStart.sh
    timeout: 180
    runas: ubuntu
  